import { useState, useMemo } from "react";
import { LogographRenderer } from "./logograph/Renderer";
import { generateLogograph } from "./logograph/Engine";
import type { LogographInput } from "./logograph/Engine";

export default function App() {
  const [activeTab, setActiveTab] = useState<"builder" | "sequence">("sequence");

  // State for single character builder
  const [builderInput, setBuilderInput] = useState<LogographInput>([0, 10, 20, 15]);

  // State for Sequence Mode
  const [sequenceString, setSequenceString] = useState<string>(
    "CIPHER ENGINE: ONLINE. AWAITING DATA-STREAM!"
  );

  const [gridCols, setGridCols] = useState<number>(4);
  const [gridRows, setGridRows] = useState<number>(3);
  const [fgColor, setFgColor] = useState<string>("#34d399"); // Emerald 400
  const [bgColor, setBgColor] = useState<string>("#020617"); // Slate 950

  const handleSliderChange = (index: number, value: number) => {
    const newArray = [...builderInput] as LogographInput;
    newArray[index] = value;
    setBuilderInput(newArray);
  };

  // Parse the input string automatically tokenizing words, punctuation, and numbers
  const sequenceChunks = useMemo(() => {
    // Match any sequence of digits OR individual valid characters
    const tokens = sequenceString.match(/\d+|[a-zA-Z,\.\!\?\:\-]/g) || [];

    const nums = tokens.map((t) => {
      // If it's a number, parse it directly
      if (/^\d+$/.test(t)) {
        return parseInt(t, 10) % 32;
      }
      
      // Otherwise, parse the character
      const char = t.toUpperCase();
      if (char >= "A" && char <= "Z") {
        return char.charCodeAt(0) - 65; // A=0, B=1 ... Z=25
      }
      
      // Map remaining punctuation
      switch (char) {
        case ",": return 26;
        case ".": return 27;
        case "!": return 28;
        case "?": return 29;
        case ":": return 30;
        case "-": return 31;
        default: return 0;
      }
    });

    const chunks: LogographInput[] = [];
    for (let i = 0; i < Math.max(nums.length, 1); i += 4) {
      chunks.push([
        nums[i] ?? 0,
        nums[i + 1] ?? 0,
        nums[i + 2] ?? 0,
        nums[i + 3] ?? 0,
      ]);
    }
    return chunks;
  }, [sequenceString]);

  // Pure SVG Exporter - Completely synchronized with LogographRenderer
  const handleExport = () => {
    const cellSize = 120; // Internal SVG grid scale
    const padding = 20;
    const width = (gridCols * cellSize) + (padding * 2);
    const height = (gridRows * cellSize) + (padding * 2);

    let svgContent = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" style="background-color: ${bgColor}; color: ${fgColor};">`;

    const maxItems = gridCols * gridRows;
    const exportChunks = sequenceChunks.slice(0, maxItems);

    exportChunks.forEach((chunk, index) => {
      const x = padding + (index % gridCols) * cellSize;
      const y = padding + Math.floor(index / gridCols) * cellSize;

      // Generate the exact same paths used by your React component
      const paths = generateLogograph(chunk);

      // Map EVERY visual property generated by the engine into SVG syntax
      const pathsSvg = paths.map(p => {
        const strokeWidth = p.strokeWidth ?? 2;
        const dashArray = p.strokeDasharray ? ` stroke-dasharray="${p.strokeDasharray}"` : "";
        const fill = p.fill ? ` fill="${p.fill}"` : " fill=\"none\"";
        const opacity = p.opacity !== undefined ? ` opacity="${p.opacity}"` : "";
        
        return `<path d="${p.d}" stroke-width="${strokeWidth}"${dashArray}${fill}${opacity} />`;
      }).join("\n          ");

      // Group the character and translate it to its grid cell.
      // Notice: stroke is set to fgColor, and color is also inherited for fill="currentColor" nodes!
      svgContent += `
        <g transform="translate(${x}, ${y})" stroke="${fgColor}" color="${fgColor}" stroke-linecap="round" stroke-linejoin="round" fill="none">
          ${pathsSvg}
        </g>`;
    });

    svgContent += `\n</svg>`;

    // Create a downloadable Blob
    const blob = new Blob([svgContent], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "cipher-sequence.svg";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Dynamically update labels based on the dominant trait (index of the highest value)
  const maxVal = Math.max(...builderInput);
  const dominantIndex = builderInput.indexOf(maxVal);

  let labels: string[] = [];
  let currentStyle = "";

  switch (dominantIndex) {
    case 0:
      currentStyle = "Emperor";
      labels = ["0. Frame (Chassis)", "1. Crown (Roof)", "2. Heart (Core)", "3. Roots (Appendages)"];
      break;
    case 1:
      currentStyle = "Celestial";
      labels = ["0. Spine (Core)", "1. Left Wing", "2. Right Wing", "3. Aura (Accents)"];
      break;
    case 2:
      currentStyle = "Prismatic";
      labels = ["0. Matrix (Grid)", "1. Facet (Cuts)", "2. Core (Jewel)", "3. Refraction (Light)"];
      break;
    case 3:
    default:
      currentStyle = "Abyssal";
      labels = ["0. Vent (Stalk)", "1. Current (Flow)", "2. Polyp (Nodes)", "3. Depth (Base)"];
      break;
  }

  const visibleSequence = sequenceChunks.slice(0, gridCols * gridRows);

  return (
    <div className="flex flex-col md:flex-row h-screen w-full bg-slate-950 text-slate-100 font-sans overflow-hidden">

      {/* Main Canvas */}
      <div className="flex-1 relative flex flex-col items-center justify-center p-8 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-slate-900 to-slate-950 overflow-y-auto">
        <div className="fixed inset-0 flex items-center justify-center pointer-events-none z-0">
          <div className="w-[40rem] h-[40rem] bg-emerald-900/10 blur-3xl rounded-full"></div>
        </div>

        <div className="relative z-10 w-full h-full flex items-center justify-center">
          {activeTab === "builder" ? (
            <div className="w-full max-w-md aspect-square flex items-center justify-center">
              <LogographRenderer
                input={builderInput}
                className="w-full h-full filter drop-shadow-[0_0_15px_rgba(52,211,153,0.3)] transition-all duration-300"
              />
            </div>
          ) : (
            // Dynamic Sequence Grid
            <div
              className="relative p-6 sm:p-10 rounded-xl shadow-2xl transition-all duration-300"
              style={{
                backgroundColor: bgColor,
                display: 'grid',
                gridTemplateColumns: `repeat(${gridCols}, minmax(0, 1fr))`,
                gridTemplateRows: `repeat(${gridRows}, minmax(0, 1fr))`,
                gap: '1.5rem'
              }}
            >
              {visibleSequence.map((chunk, idx) => (
                <div key={idx} className="w-16 h-16 sm:w-24 sm:h-24 flex items-center justify-center">
                  <div style={{ color: fgColor }} className="w-full h-full">
                    <LogographRenderer
                      input={chunk}
                      overrideColor={fgColor}
                      className="w-full h-full drop-shadow-lg transition-colors duration-300"
                    />
                  </div>
                </div>
              ))}

              {/* Render empty placeholders if the sequence is shorter than the grid */}
              {Array.from({ length: Math.max(0, (gridCols * gridRows) - visibleSequence.length) }).map((_, i) => (
                <div key={`empty-${i}`} className="w-16 h-16 sm:w-24 sm:h-24 border border-dashed border-slate-700/30 rounded-lg"></div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Control Sidebar */}
      <div className="w-full md:w-80 lg:w-96 bg-slate-900/90 backdrop-blur-xl border-t md:border-t-0 md:border-l border-slate-800/80 p-6 sm:p-8 flex flex-col gap-8 shadow-2xl z-20 shrink-0 overflow-y-auto">

        <div>
          <h1 className="text-2xl font-bold bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent mb-2">
            Cipher Engine
          </h1>
          <p className="text-slate-400 text-sm leading-relaxed">
            Construct single symbols or write complete encrypted sequences.
          </p>
        </div>

        {/* Tabs */}
        <div className="flex bg-slate-950/50 p-1 rounded-lg border border-slate-800">
          <button
            onClick={() => setActiveTab("builder")}
            className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${activeTab === "builder" ? "bg-slate-800 text-emerald-400 shadow-sm" : "text-slate-400 hover:text-slate-200"
              }`}
          >
            Builder
          </button>
          <button
            onClick={() => setActiveTab("sequence")}
            className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${activeTab === "sequence" ? "bg-slate-800 text-emerald-400 shadow-sm" : "text-slate-400 hover:text-slate-200"
              }`}
          >
            Sequence
          </button>
        </div>

        {activeTab === "builder" ? (
          <div className="space-y-6 flex-1">
            <div className="flex justify-between items-center mb-[-10px] mt-2">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Active Morphology</span>
              <span className="text-xs font-bold text-emerald-400 bg-emerald-900/20 px-2 py-1 rounded border border-emerald-800/30">{currentStyle}</span>
            </div>
            <div className="space-y-6">
              {builderInput.map((val, idx) => (
                <div key={idx} className="space-y-3 group">
                  <div className="flex justify-between items-center">
                    <label className="text-sm font-medium text-slate-300 group-hover:text-slate-100 transition-colors">
                      {labels[idx]}
                    </label>
                    <span className="text-emerald-400 font-mono text-sm bg-emerald-900/20 px-2 py-0.5 rounded border border-emerald-800/30">
                      {val}
                    </span>
                  </div>
                  <input
                    type="range"
                    min="0"
                    max="31"
                    value={val}
                    onChange={(e) => handleSliderChange(idx, parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-emerald-500 hover:accent-emerald-400 transition-all focus:outline-none focus:ring-2 focus:ring-emerald-500/20"
                  />
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div className="flex flex-col flex-1 h-full gap-6">
            {/* Data Stream */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-300">Data Stream</label>
              <textarea
                value={sequenceString}
                onChange={(e) => setSequenceString(e.target.value)}
                placeholder="Enter text or numbers..."
                className="w-full h-32 bg-slate-950/50 border border-slate-800 rounded-lg p-3 font-mono text-sm text-emerald-400 focus:outline-none focus:border-emerald-500/50 resize-none"
              />
            </div>

            {/* Grid & Style Controls */}
            <div className="grid grid-cols-2 gap-4 border-t border-slate-800 pt-6">
              <div className="space-y-2">
                <label className="text-xs font-semibold text-slate-400 uppercase">Columns</label>
                <input
                  type="number"
                  min="1"
                  max="20"
                  value={gridCols}
                  onChange={(e) => setGridCols(Math.max(1, parseInt(e.target.value) || 1))}
                  className="w-full bg-slate-950/50 border border-slate-800 rounded-lg p-2 text-white font-mono text-sm"
                />
              </div>
              <div className="space-y-2">
                <label className="text-xs font-semibold text-slate-400 uppercase">Rows</label>
                <input
                  type="number"
                  min="1"
                  max="20"
                  value={gridRows}
                  onChange={(e) => setGridRows(Math.max(1, parseInt(e.target.value) || 1))}
                  className="w-full bg-slate-950/50 border border-slate-800 rounded-lg p-2 text-white font-mono text-sm"
                />
              </div>
              <div className="space-y-2">
                <label className="text-xs font-semibold text-slate-400 uppercase">Ink Color</label>
                <input
                  type="color"
                  value={fgColor}
                  onChange={(e) => setFgColor(e.target.value)}
                  className="w-full h-10 bg-slate-950/50 border border-slate-800 rounded-lg cursor-pointer p-1"
                />
              </div>
              <div className="space-y-2">
                <label className="text-xs font-semibold text-slate-400 uppercase">Paper Color</label>
                <input
                  type="color"
                  value={bgColor}
                  onChange={(e) => setBgColor(e.target.value)}
                  className="w-full h-10 bg-slate-950/50 border border-slate-800 rounded-lg cursor-pointer p-1"
                />
              </div>
            </div>

            <button
              onClick={handleExport}
              className="mt-4 w-full bg-emerald-600 hover:bg-emerald-500 text-white font-semibold py-3 px-4 rounded-lg shadow-lg shadow-emerald-900/50 transition-all active:scale-[0.98]"
            >
              Export as SVG
            </button>
          </div>
        )}

      </div>
    </div>
  );
}